### ISSUE TITLE
숙제1 README 파일에 오타가 있는 것 같습니다.

### ISSUE THREAD

**Issue by Chavo-Kim** [Sung-HwanLee/swpp202101-assn1#1]
4. 설명 마지막에 있는

`git log --online --no-merges`가 `git log --oneline --no-merges` 으로 수정되어야 할 것 같습니다.

**Comment by Sung-HwanLee** [comment]
정정 감사합니다.
다만, 과제 특성상 repo를 수정하면 과제에 영향이 가기 때문에 수정은 어려울 것 같습니다.
